module.exports = {
    join: require('../join'),
    leave: require('../leave'),
    play: require('../play'),
    search: require('../search'),
    stop: require('../stop'),
    resume: require('../resume'),
    skip: require('../skip'),
    getVolume: require('../getVolume'),
    setVolume: require('../setVolume'),
    queue: require('../queue'),
    selectInQueue: require('../selectInQueue'),
    clearQueue: require('../clearQueue'),
    random: require('../random'),
    help: require('../help'),
}